const attrNameData = [
    { key: 'grid', label: '视图' }, 
    { key: 'show', label: '显示' }, 
    { key: 'left', label: '左边距' }, 
    { key: 'right', label: '右边距' }, 
    { key: 'top', label: '上边距' },  
    { key: 'bottom', label: '下边距' },  
    { key: 'xAxis', label: 'x轴' }, 
    { key: 'position', label: '位置' }, 
    { key: 'name', label: '名称' }, 
    { key: 'nameLocation', label: '名称位置' }, 
    { key: 'nameGap', label: '轴/名称间距' }, 
    { key: 'inverse', label: '反向坐标轴' }, 
    { key: 'boundaryGap', label: '两边留白' },
    { key: 'nameTextStyle', label: '名称文本样式' },
    { key: 'color', label: '颜色' }, 
    { key: 'fontSize', label: '字体大小' }, 
    { key: 'fontWeight', label: '字体粗细' }, 
    { key: 'fontFamily', label: '字体' }, 
    { key: 'axisLabel', label: '标签' }, 
    { key: 'rotate', label: '旋转' }, 
    { key: 'align', label: '对齐方式' }, 
    { key: 'margin', label: '距离轴线' }, 
    { key: 'axisLine', label: '轴线' }, 
    { key: 'width', label: '宽度' }, 
    { key: 'type', label: '类型' }, 
    { key: 'axisTick', label: '刻度' }, 
    { key: 'alignWithLabel', label: '与标签对齐' }, 
    { key: 'splitLine', label: '分割线' }, 
    { key: 'splitArea', label: '分割区域' }, 
    { key: 'yAxis', label: 'y轴' }, 
    { key: 'min', label: '区间最小值' }, 
    { key: 'max', label: '区间最大值' }, 
    { key: 'title', label: '图表标题' }, 
    { key: 'text', label: '主标题' }, 
    { key: 'link', label: '主超链接' }, 
    { key: 'subtext', label: '副标题' }, 
    { key: 'sublink', label: '副超链接' }, 
    { key: 'textAlign', label: '位置' }, 
    { key: 'textVerticalAlign', label: '垂直对齐' }, 
    { key: 'padding', label: '内边距' }, 
    { key: 'itemGap', label: '间隔' }, 
    { key: 'textStyle', label: '主标题文本样式' }, 
    { key: 'subtextStyle', label: '副标题文本样式' }, 
    { key: 'legend', label: '图例' }, 
    { key: 'selectedMode', label: '选择模式' }, 
    { key: 'icon', label: '图标' }, 
    { key: 'itemWidth', label: '图标宽度' }, 
    { key: 'itemHeight', label: '图标高度' }, 
    { key: 'backgroundColor', label: '背景色' }, 
    { key: 'borderColor', label: '边框颜色' }, 
    { key: 'borderWidth', label: '边框宽度' },
    { key: 'borderRadius', label: '边框半径' }, 
    { key: 'shadowBlur', label: '阴影大小' }, 
    { key: 'shadowColor', label: '阴影颜色' }, 
    { key: 'shadowOffsetX', label: '阴影X偏移' }, 
    { key: 'shadowOffsetY', label: '阴影Y偏移' }, 
    { key: 'pageButtonItemGap', label: '按钮间距' }, 
    { key: 'pageButtonGap', label: '距离图例' }, 
    { key: 'pageButtonPosition', label: '控制块位置' }, 
    { key: 'pageIconColor', label: '按钮颜色' }, 
    { key: 'pageIconInactiveColor', label: '禁按颜色' }, 
    { key: 'pageIconSize', label: '按钮大小' }, 
    { key: 'pageTextStyle', label: '按钮样式' }, 
    { key: 'tooltip', label: '提示框' }, 
    { key: 'trigger', label: '触发类型' }, 
    { key: 'showDelay', label: '触发类型' }, 
    { key: 'toolbox', label: '工具栏' }, 
    { key: 'feature', label: '功能按钮' }, 
    { key: 'saveAsImage', label: '保存图片' }, 
    { key: 'restore', label: '配置项还原' }, 
    { key: 'dataView', label: '数据视图工具' }, 
    { key: 'orient', label: '布局方式' }, 
    { key: 'itemSize', label: '图标大小' }, 
    { key: 'style', label: '基础样式' }, 
     
    { key: 'borderStyle', label: '边框风格' }, 
    { key: 'height', label: '高' }, 
    { key: 'lineHeight', label: '行高' }, 
    // { key: 'letterSpacing', label: '字间距' }, 
    // { key: 'textAlign', label: '左右对齐' }, 
    { key: 'verticalAlign', label: '上下对齐' },
    { key: 'opacity', label: '透明度' }, 
    { key: 'series', label: '系列' },
    { key: 'content', label: '内容' },
    { key: 'number', label: '数字' },
    { key: 'prefix', label: '前缀' },
    { key: 'suffix', label: '后缀' },
    { key: 'paddingLeft', label: '对齐边距' },
    { key: 'marginLeft', label: '对齐边距' },

];
// 系列相关
const seriesNameData = [
    // 折线图
    { key: 'type', label: '类型' }, 
    { key: 'name', label: '名称' }, 
    { key: 'smooth', label: '平滑曲线' }, 
    { key: 'lineStyle', label: '折线样式' }, 
    { key: 'color', label: '颜色' }, 
    { key: 'width', label: '宽度' }, 
    { key: 'type', label: '类型' }, 
    { key: 'symbol', label: '拐点图形' }, 
    { key: 'symbolSize', label: '拐点大小' }, 
    { key: 'itemStyle', label: '拐点样式' }, 
    { key: 'borderColor', label: '描边颜色' }, 
    { key: 'borderWidth', label: '描边线宽' }, 
    { key: 'borderType', label: '描边类型' }, 

    { key: 'label', label: '文本标签' }, 
    { key: 'show', label: '显示' }, 
    { key: 'formatter', label: '内容格式' }, 
    { key: 'position', label: '位置' }, 
    { key: 'fontSize', label: '字体大小' }, 
    { key: 'fontWeight', label: '字体粗细' }, 
    { key: 'fontFamily', label: '字体' }, 
    
    { key: 'animation', label: '开启动画' }, 
    { key: 'animationDuration', label: '动画的时长' }, 
    { key: 'animationEasing', label: '动画效果' }, 
    // 柱状图
    { key: 'barWidth', label: '柱形宽度' }, 
    { key: 'barMinHeight', label: '最小高度' }, 
    { key: 'barGap', label: '不同类目间距' }, 
    { key: 'barCategoryGap', label: '同类目间距' }, 
    { key: 'barCategoryGap', label: '同类目间距' }, 
    { key: 'borderRadius', label: '圆角' }, 
    // 柱背景
    { key: 'showBackground', label: '显示柱背景' }, 
    { key: 'backgroundStyle', label: '柱背景样式' }, 
]
export {
    attrNameData,
    seriesNameData
}